### ISSUE TITLE
Criar inserção de abastecimento de bico movel (mostrar campos do encerrante e baixar estoque)

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#10]

**Comment by marcioelias** [comment]
- [x] Alterado layout da tela de Novo/Alterar Abastecimetos para mostrar os campos referentes a automação antes dos campos de combustível e valores
 - [x] Encerrante Inicial deve ser preenchido automaticamente com o encerrante atual do bico na base de dados.
 - [x] Combustível deve ser selecionado automaticamente ao selecionar o bico
 - [x] Valor do combustível deve ser obtido automaticamente ao selecionar o combustível
 - [x] Setar automaticamente o encerrante final do abastecimento ao informar a quantidade abastecida, somando-se ao encerrante inicial.

**Comment by marcioelias** [comment]
Tela de inclusão de abastecimento concluida. Falta analisar como fazer a alteração, para contemplar abastecimentos manuais e oriundos de automação.
