### ISSUE TITLE
Posicao de estoque do tanque

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#17]
o campo posicao de estoque do tanque nao esta atualizando apos entrada de estoque.o
relatorio de posicao grafico atualiza

**Comment by marcioelias** [comment]
Para contornar esse problema será necessário uma implemnetação mais apurada do controle do estoque de combustíveis.

- Criar uma tabela para armazenar as movimentaçẽos de combustíveis contendo
    - data
    - tanque
    - quantidade
    - tipo de operação (entrada/saída)

- Alimentar a tabela de movimentações:
    - A cada abastecimento
    - A cada entrada de combustível

- Alterar o gráfico de posição de tanque para que use os registros da tabela de movimentação

**Comment by marcioelias** [comment]
Aplicado um grande desenvolvimento para suprir todas as demandas listadas acima.

Agora, a cada entrada de combustivel (atualizada para ficar no padrão da entrada de produtos), ocorre uma movimentação de entrada de combustivel no tanque.

Assim como para cada abastecimento, ocorre uma saida de combustivel do tanque.

Tanto o gráfico de posição do tanque, quanto o relatório de listagem de tanques já foram atualizados para utilizar a nova estrutura de dados.

Vou considerar fechado, e aguardar os testes de vocês.
