### ISSUE TITLE
inclusao de abastecimento

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#18]
atualmente o valor total é calculando qndo sai do edit de valor unitario, o ideal seria qndo sair do edit quantidade pois se digitar a quantidade e clicar no ok da erro pois fica em branco o edit total

**Comment by marcioelias** [comment]
Você está fazendo isso selecionando Bico ou não selecionando?

Está programado para disparar o evento de calculo tanto ao soltar uma tecla quanto ao sair (perder o foco), tanto do campo de quantidade quanto do campo de valor unitário.

Não consegui reproduzir esse problema.

**Comment by renatoxokleng** [comment]
testei informando o bico. Fiz com o celular vou testar pelo pc

**Comment by marcioelias** [comment]
Deu tudo certo?

Podemos fechar esse ticket?

**Comment by marcioelias** [comment]
Fechado por inatividade.
