### ISSUE TITLE
Calculo de media na inclusao de abastecimento

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#21]
o calculo nao esta correto na inclusao de abastecimento

**Comment by marcioelias** [comment]
Supondo o seguinte:

KM 1000 Abasteceu 50 - média 10
KM 2000 Abasteceu 50 - média 20

Ou seja, tinha um abastecimento de 50 em torno de 1500 KM que precisa ser inserido, porém a média não era calculada.

Foi feito um ajuste para sempre que for inserido um abastecimento no sistema, de acordo com a data do abastecimento, será usado como base para cálculo de média o abasteciemento de data diretamente inferior ao atual.

Bem como todos os abastecimentos já registrados com data superior ao abasteciemento atual, terão sua média recalculada.
