### ISSUE TITLE
ABA MOVIMENTAÇÃO DE COMBUSTIVEL

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#24]
Colocar colunas:
  -  Média KM
  -  KM anterior 
  -  ~~KM atual~~
  -  Distância Percorrida

**Comment by marcioelias** [comment]
Esse tipo de informação não pode ser computada no momento da exibição, por que vai causar um impacto significativo na performance da aplicação, agravado progressivamente com o aumento do volume de informações na base.

A saída seria no momento da gravação do abastecimento, buscar o abastecimento anterior do veículo e inserir a KM, bem como a KM percorrida (diferença do odômetro entre o abastecimento atual e o anterior).

Com isso surge uma dúvida

- Da mesma forma que a média, será necessário recalcular todos os abastecimentos futuros em caso de inclusão de um abastecimento que não seja o último?
- Outra coisa, a média não fica armazenada, e sim é calculada. Se for para fazer esse controle vou ter que passar a armazená-la.

**Comment by renatoxokleng** [comment]
è um item a pensar!
Uma alternativa: tem como  colocar um botao ao lado de incluir com a função: Mostar média
Ai ele colocaria uma coluna da média do veiculo apenas para aquela pagina... nao sei se fica bom, mas  a informacao naquela tela é importante...

**Comment by renatoxokleng** [comment]
colocar apenas a coluna media e mostrar a que esta salvo na tabela abastecimento

**Comment by marcioelias** [comment]
Implementada a coluna com a média de consumo do veículo no abastecimento.
