### ISSUE TITLE
Alterar menus

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#25]
Menu: Configurações (pedir senha máster)
Cadastros: 
- TANQUES
 – BOMBAS 
–  BICOS 
– TIPO DE BOMBA 
– MODELO DE BOMBA 
– CONTROLE DE ACESSO (usuários, perfis de acesso, associação)

**Comment by marcioelias** [comment]
- Reconfigurado o layout dos menus do sistema
- Adicionado nível de acesso ao menu de configurações somente a os perfis:
   - super
   - administrador

**Mesmo que o perfil do usuário tenha permissões para acessar os itens dos submenus inclusos no menu configurações, somente os perfis listados acima verão o menu***
