### ISSUE TITLE
O.S. erro ao editar e salvar (excluir, alterar) mesmo sem alterar nada

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#26]
O.S. erro ao editar e salvar (excluir, alterar) mesmo sem alterar nada,
Devemos considerar também: ao excluir a mensagem que aparece: Remover Ordem de Serviço: 2? colocar que ele vai devolver o estoque para o sistema. e alguma imagem de atenção!

Type error: Argument 1 passed to Illuminate\Database\Eloquent\Relations\HasOneOrMany::createMany() must be of the type array, null given, called in /home/goldense/demo.goldenservice.com.br/app/Http/Controllers/OrdemServicoController.php on line 239

**Comment by renatoxokleng** [comment]
Deixar gravar o campo Observacao em branco (da erro se gravar)

**Comment by marcioelias** [comment]
O problema estava em gravar a OS sem qualquer serviço, e/ou produto associado. No cadastro é possível, mais na alteração não estava sendo.

Foi implementado uma verificação dos dados postados para constatar se há produtos ou serviços a serem incluídos antes de tentar incluir.
