### ISSUE TITLE
Impressão de Entrada de Combustíveis

### ISSUE THREAD

**Issue by marcioelias** [marcioelias/goldenfrota#27]
Implementar a possibilidade de impressão da entrada de combustíveis, assim como acontece para a entrada de produtos.

**Comment by renatoxokleng** [comment]
Quando criar a funcao, colocar filtros:
Entrada/Saida/todos
Tanques: 1, 2, 3, (posibilidade de marcar 1 e 3)

**Comment by marcioelias** [comment]
Quando defini isso pra não esquecer, a ideia era fazer igual a entrada de produtos, na relação das entradas, tem um botão visualizar ao lado do editar e do excluir, que possibilita visualizar (e também imprimir) a nota.

> Quando criar a funcao, colocar filtros:
Entrada/Saida/todos
Tanques: 1, 2, 3, (posibilidade de marcar 1 e 3)

Isso seria para um relatório de entradas. Também tem que ser feito, mais ai é outra issue.

**Comment by marcioelias** [comment]
Implementado visualização de NF de entrada de combustível. acessível atravez do icone:
![image](https://user-images.githubusercontent.com/2084051/46391970-db92a080-c6b5-11e8-84be-068eff61c029.png).
Menu: Movimentação / Entrada de Combustíveis
