### ISSUE TITLE
Movimentacao de combustivel (entradas e saldo) em branco (prefeitura)

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#29]
Marcio, o relatorio de estoque do tanque (Posicao do tanque - grafico) está com saldo em branco
entao fui ver a movimentacao de entrada dos combustiveis, e esta zerado.

**Comment by marcioelias** [comment]
Quanto a movimentação de estoque de combustíveis foram encontrados 2 problemas.

 - ~~Abastecimentos vindos da automação não movimentariam o estoque.~~ 75f6839
 - ~~Necessidade de uma tela para ajustes no estoque dos tanques.~~ Aberto novo issue para tratar desta funcionalidade #30 

> Como foi totalmente re-escrita a parte de movimentação de combustíveis, os controles de estoques antigos se perderam. Não se tinha transações no modelo antigo, apenas o saldo do tanque era atualizado. Com o modelo atual, cada movimentação gera um registro de transação que é contabilizado para gerar o saldo em estoque.
