### ISSUE TITLE
Tela de Manutenção de Veículo

### ISSUE THREAD

**Issue by marcioelias** [marcioelias/goldenfrota#3]
- [x] Criar uma tela que irá tratar de manutenções dos veiculos. Essa tela deverá conter:

  - Cliente
  - Departamente (opcional)
  - Veículo
  - ~~Data (atual por padrão)~~
  - Data de Abertura (atual por padrão)
  - Data de Fechamento (preenchida automaticamente com a data do fechamento)
  - KM do veículo no momento da manutenção
  - Descrição das manutenções realizadas
  - Relação de produtos utilizados (Óleos, Filtros, Pneus, etc). 
  - Status (fechada, em aberto)

- [x] Movimentação de estoque
  - [x] Movimentar o estoque ao inserir a OS (mesmo que em aberto)
  - [x] Remover todas as movimentações da OS ao alterar a mesma, e inserir todas novamente.

- [x] Ao alterar uma Manutenção de Aberta para Fechada:
  ~~Movimentar o estoque dos produtos utilizados~~ 
  - [x] Impossibilitar novas alterações

- [x] Botão para imprimir uma Manutenção na tela de listagem de Manutenções.

**Comment by marcioelias** [comment]
Tela encontra-se ainda em desenvolvimento.

esta atrasada mais vai sair em nos próximos dias.

Juntamente com essa tela já vou subir outras implementações e correções que já foram discutidas em outros posts aqui no projeto.

**Comment by marcioelias** [comment]
Faltando apenas os relatórios referentes a Ordem de Serviço.

Restante está implementado. Qualquer problemas referente a essa feature, comentem aqui neste issue.

**Comment by renatoxokleng** [comment]
Uma grande coisa que poderiamos fazer é a OS ser tipo esse sistema, Abro uma o.s. e posso ir atualizando ela até fechar.

**Comment by marcioelias** [comment]
> Uma grande coisa que poderiamos fazer é a OS ser tipo esse sistema, Abro uma o.s. e posso ir atualizando ela até fechar.

Não entendi. Isso já pode ser feito, enquanto não fechar a OS pode-se alterá-la e atualizá-la como desejar.

Se tiver alguma coisa implementação diferenciada que eu não tenha entendido, pode explicar em mais detalhes.

**Comment by marcioelias** [comment]
Desenvolvimento concluído.
