### ISSUE TITLE
Campos Obrigatorios da O.S

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#32]
Permitir inserir os com o campo observação nulo.
Permitir km do veiculo nulo ou alertar o usuario para digitar

**Comment by marcioelias** [comment]
> ~~[ 1 ] Permitir inserir os com o campo observação nulo.~~
~~[ 2 ] Permitir km do veiculo nulo ou alertar o usuario para digitar~~

- 1 Campo Observação é opcional
- 2 Campo KM do veículo deve ser um número > 0
