### ISSUE TITLE
O.S Visualização 

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#33]
Na visualização da O.S , adicionar a coluna valor unitario para os produtos
na linha dos serviços adicionar a coluna quantidade.

**Comment by marcioelias** [comment]
> [ 1 ] ~~Na visualização da O.S , adicionar a coluna valor unitario para os produtos~~
[ 2 ] ~~na linha dos serviços adicionar a coluna quantidade.~~

- [ 1 ] Campo implementado na visualização.
- [ 2 ] Não existe essa informação para **Serviços**. Ou seja, podem ser realizados diversos serviços na mesma OS, porém não faz sentido executar o mesmo serviço várias vezes, sendo que uma OS está diretamente atrelada a um veículo.
