### ISSUE TITLE
Relatorio de Abastecimento - ordenar por data

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#34]
Ordernar por data, atualmente esta por id

**Comment by marcioelias** [comment]
> ~~Ordernar por data, atualmente esta por id~~

Alteração realizada.

**Comment by marcioelias** [comment]
Havia faltado a alteração na tela inicial que mostra a listagem de abastecimentos.

Foi implementada a mesma alteração em:

 - Movimentação/Abastecimentos
