### ISSUE TITLE
Cadastro de Produtos - mascara para valor custo e venda

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#37]
Corrigir mascara do valor de custo e venda, esta aceitando digitar ponto ou virgula, mas se colocar virgula ocorre erro ao inserir no banco

**Comment by marcioelias** [comment]
Alterado o tipo de campo para Number (aceitando assim a vírgula na tela de cadastro e alteração).

Alterado a tela de listagem de produtos para mostrar os valores de custo e venda formatados.
