### ISSUE TITLE
Cadastro de produtos - vencimento em dias

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#38]
CAMPO VENCIMENTO EM DIAS, ALTERAR EDIT PARA ACEITAR APENAS NUMEROS INTEIROS, ATUALMENTE
ESTA ACEITANDO QUALQUER CARACTER

**Comment by marcioelias** [comment]
Alterado o campo Vencimento em dias tanto no cadastro quanto na alteração do produto para aceitar somente os digitos [0-9].
