### ISSUE TITLE
CADASTRO DE GRUPO DE PRODUTOS - inativos

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#40]
MESMO MARCADO O GRUPO COMO ATIVO = NAO
O GRUPO É LISTADO DURANTE O CADASTRO DE UM NOVO PRODUTO.

**Comment by marcioelias** [comment]
Alterado a tela de cadastro de produtos para listar somente:
- Unidades (Ativos)
- Grupo de Produtos (Ativos)
- Fornecedores (Ativos)
- Estoques (Ativos)

Alterado a tela de alteração de produtos para listar somente:
- Unidades (Ativos + relacionados)
- Grupo de Produtos (Ativos + relacionados)
- Fornecedores (Ativos + relacionados)
- Estoques (Ativos + relacionados)

Ou seja, ao inativar qualquer um dos cadastros acima, ele deixa de aparecer para novos cadastros de produtos, mais ao editar um produto que tenha algum dos itens desativados previamente relacionado, ele continua aparecendo. 

Caso seja desfeita a associação, o item desativado não volta a aparecer a menos que seja reativado, para então poder ser re-associado ao cadastro de produtos.
