### ISSUE TITLE
ORDEM DE SERVIÇOS - SALDO DE PRODUTOS NA O.S

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#41]
AO INSERIR UM ITEM NA ORDEM DE SERVIÇOS,
ESTA LISTANDO APENAS PRODUTOS COM SALDO EM ESTOQUE.
DEVERIA LISTAR TODOS E EMITIR MSG AO INSERIR O ITEM, DE QUE NAO POSSUI SALDO SUFICIENTE, OU NO CADASTRO DO PRODUTO, MARCAR SE PODE MOVIMENTAR E FICAR NEGATIVO.

**Comment by marcioelias** [comment]
Hoje esse controle é feito no estoque. Ele é que permite ou não movimentar produtos que venham a ficar com estoque negativo.

Seria o caso de adicionar o controle ao cadastro de cada produto individualmente?

Não vai abrir brechas esse tipo de alteração, do tipo que o gerente configura o estoque e desativa a opção que possibilita o estoque negativo dos produtos, e alguém que possa alterar o cadastro do produto seta que o mesmo pode ficar com estoque negativo. 

Neste caso não importa a configuração do estoque, ou em quantos estoques aquele produto esteja relacionado, será sempre possível movimentá-lo na venda.

**Comment by marcioelias** [comment]
Alterado o código para permitir listar todos os produtos, mesmo os com estoque zerado. Caso o estoque selecionado permita trabalhar com estoque negativo, ainda que o produto esteja com estoque zerado será permitida a movimentação de venda.

Caso o estoque selecionado não permita estoque negativo, será emitido uma mensagem de erro ao inserir o produto, informando que a quantidade informada excede o saldo atual em estoque, apresentando a quantidade atual do produto em estoque.

Esse controle serve para produtos em estoque também, caso a quantidade informada seja maior que a em estoque, e o estoque não esteja configurado para permitir negativar saldo de produtos, a mesma mensagem será apresentada negando a utilizaão daquela quantidade.
