### ISSUE TITLE
ORDEM DE SERVIÇOS- CAMPO OBSERVAÇÃO NULO

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#42]
CAMPO OBSERVAÇÃO, PERMITIR QUE SEJA NULO. ATUALMENTE SE DEIXAR EM BRANCO
DA ERRO AO INSERIR NO BANCO

**Comment by marcioelias** [comment]
Já é permitido o cadastro de OS com o campo de observação em branco.

Favor conferir novamente.

**Comment by marcioelias** [comment]
Já corrigido, será testado na base de dados atual, caso tenha ficado alguma alteração de banco a ser realizada para traz, será feito manualmente.
