### ISSUE TITLE
CADASTRO DE SERVIÇOS - ERRO AO CADASTRAR

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#43]
CADASTRO DE SERVIÇOS - Oops... Ocorreu um erro. The given data was invalid..

**Comment by marcioelias** [comment]
Provavelmente algum problema relacionado a formatação de dados decimais.

Vou verificar.

**Comment by marcioelias** [comment]
Identificada falha na rotina de validação dos dados, a qual estava retornando uma exceção ao invéz das mensagens de validação.

Foram efetuadas as correções necessárias.
