### ISSUE TITLE
TELA DE CADASTRO DE ABASTECIMENTO - 

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#44]
NA TELA DE CADASTRO DE ABASTECIMENTOS
O CALCULO DO VALOR TOTAL, ESTA FAZENDO QUANDO SAI DO CAMPO VALOR UNITARIO
MAS COMO JA VEM PREENCHIDO O VALOR UNITARIO, DEVERIA SER FEITO QUANDO SAI DOS 2 CAMPOS
QUANTIDADE E VALOR UNITARIO, POIS ASSIM, SE O USUARIO APENAS DIGITAR A QUANTIDADE, O CALCULO É FEITO.

**Comment by marcioelias** [comment]
Correção implementada.
