### ISSUE TITLE
FUNÇAO PARA AFERIÇÃO DA BOMBA

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#45]
REALIZAR FUNÇÃO COM NIVEL DE ACESSO, PARA REALIZAR A AFERIÇÃO DA BOMBA.

**Comment by marcioelias** [comment]
Como seria essa aferição?

 - Selecionado um abastecimento.
 - Inserir de uma movimentação de entrada no tanque na quantidade do abastecimento
 - Identificar como Aferição

Em outras palavras, seria uma tela de cadastro de aferição, e ao clicar em cadastrar apareceriam todos os abastecimentos que ainda não estivessem relacionados com aferição. 

Uma vez selecionado o abastecimento e salvo o registro, as operações acima seriam executadas pelo sistema.

**Comment by renatogolden** [comment]
Exato! Pode ser um votao, ali junto com excluir, ou clicar em editar e se a pessoa tiver acesso aparecer o botao de: ( ) MARCAR COMO AFERIÇÃO

**Comment by marcioelias** [comment]
Implementação concluída, seguem as regras do caso de uso.

- Criado permissão 'Cadastrar Afericao' para condicionar o acesso a essa funcionalidade
- Criado um campo para identificar se o abastecimento é uma aferição
- Criado um botão para fazer do abasteciemento uma aferição na listagem de abastecimentos
- Possibilidade de criação de Aferições para abasteciementos que:
  - Ainda não estejam relacionados a uma aferiçaõ
  - Tenham algum bico relacionado
  - Tenham sido realizados após a última grande atualização do sistema que alterou a movimentação do estoque de combustível.
- Uma vez executada a ação serão desempenhadas as seguintes operações internamente pelo sistema:
  - Inclusão de um registro na tabela aferições, contendo
    - ID do Abastecimento
    - ID do usuário que efetuou a operação
    - Data/Hora da operação
  - Remoção do ID do abastecimento selecionado da movimentação de saída de combustível
  - Adição do ID da Aferição (incluido na tabela aferições) no campo afericao_id do mesmo registro
  - Alteração do tipo de movimentação, de Abastecimento para Saída - Aferição
  - Inclusão de um novo registro na tabela de movimentação de combustíveis com:
    - Campo afericao_id = ID da aferição incluída
    - Tipo de Movimentação como Entrada - Aferição
    - Volume movimentado referente ao mesmo do Abastecimento selecionado no início da operação

Qualquer que seja o erro que possa vir a ocorrer durante a execução de qualquer um dos passos acima acarreta em uma exceção que irá reverter todo o processo na base de dados (rollback).

Uma dúvida ficou quanto a obrigatoriedade de campos no cadastro de abastecimentos. Hoje não é possível incluir um abastecimento (manualmente pelo menos) sem informar um veículo e sua KM (para informar o veículos por sua vez tem que ser selecionado um cliente). Em se tratando de Aferição essa regra não faria muito sentido.

Analisar uma forma de flexibilizar isso.

Ideia:
 - Um campo no cadastro de abastecimento dizendo que se trata de uma aferição (com isso todo o processo da aferição seria realizado no momento de salvar o abastecimento).

Se a ideia acima for aceita, condicionar esse campo a permissão de Cadastro de Aferição?

**Comment by marcioelias** [comment]
Favor verificar e reportar aqui para que possa concluir esse issue.

**Comment by renatogolden** [comment]
Ideia:

Um campo no cadastro de abastecimento dizendo que se trata de uma aferição (com isso todo o processo da aferição seria realizado no momento de salvar o abastecimento).

Gostei dessa ideia, coloca um botao tipo aquele de liga e desliga...

**Comment by marcioelias** [comment]
> Gostei dessa ideia, coloca um botao tipo aquele de liga e desliga...

Vinculado a permissão para poder utilizar?

**Comment by marcioelias** [comment]
Seguindo a ideia inicial:
 - Adicionado componente a tela de cadastro de abastecimentos, para informar se trata-se de uma aferição, em caso positivo:
    - Cliente, Veículo e KM do Veículo passam a não ser necessários
    - Bico passa a ser obrigatório
- Em caso de ser um abastecimento normal
    - Cliente, Veículo e KM do Veículo passam a ser obrigatórios
    - Bico não é obrigatório

O componente está ativo na tela de cadastro, de forma que é possível incluir um abastecimento diretamente informando ser uma aferição, que todas as movimentações de estoque serão realizadas de acordo.

Na tela de edição do abastecimento no entanto, esse componente fica desativado, aparecendo unica e exclusivamente para informar se trata-se ou não de uma aferição.

Em caso de Aferição, não é mais possível editar o abastecimento, mesmo que seja possível acessar a tela de edição todos os campos são desabilitados, e ao enviar o formulário nada é processado no lado do servidor.

Para tornar um abastecimento em aferição, uma vez que já tenha sido efetuado seu cadastro, ou que o mesmo tenha vindo via automação, continua valento a opção do botão **Aferição** na listagem de abasteciementos.

Além disso no que tange a permissionamento, foi configurado o sistema para mostrar o campo de aferição na tela de cadastramento de abastecimento somente se o usuário logado tiver permissão para cadastrar uma aferição.

Bem como o botão para tornar um abastecimento em aferição também fica visível somente mediante a permissão no perfil do usuário.

Com essas implementações vou fechar esse issue.

Se tiver alguma questão a respeito dessa feature abrir outro issue.
