### ISSUE TITLE
CALCULO DE MEDIA NA EDIÇÃO DO ABASTECIMENTO

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#46]
AO EDITAR UM ABASTECIMENTO, A MEDIA ATUAL É ALTERADA AUTOMATICAMENTE
PARA UMA MEDIA INCORRETA.

**Comment by marcioelias** [comment]
Em alguns testes não foi possível constatar o problema.

Se conseguirem fazer um cenário para reproduzir esse erro no sistema de demonstração.

O Código utilizado para Cadastrar ou Alterar abastecimentos referente ao cálculo da média é identico.

`$abastecimento->media_veiculo = $this->obterMediaVeiculo(Veiculo::find($request->veiculo_id), $abastecimento);`

**Comment by renatogolden** [comment]
Pois é! Pode fechar  a insue

**Comment by marcioelias** [comment]
Ok, se notarem alguma anomalia, abram com um exemplo que eu analiso novamente.
