### ISSUE TITLE
ENTRADA NO TANQUE- CAMPO SERIE NULO

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#47]
PERMITIR CAMPO SERIE NULO

**Comment by marcioelias** [comment]
Implementação realizada.

Requer alteração na base de dados.

precisa rodar o comando:

`php artisan migrate`

esse comando irá excluir a coluna serie da tabela e recriar permitindo NULL. Sendo assim se houver alguma NF cadastrada que tenha essa informação, a mesma será perdida durante a atualização.
