### ISSUE TITLE
RELATORIO DE MOVIMENTAÇÃO DE ESTOQUE PRODUTOS - SINTETICO/ANALITICO

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#49]
CRIAR RELATORIO DE MOVIMENTAÇÃO DE ESTOQUE COM OPÇÃO DE SELECIONAR ANALITICO, SINTETICO
AGRUPAR POR TIPO DE MOVIMENTAÇÃO

**Comment by marcioelias** [comment]
Consegue me exemplificar como ficaria o sintético e analítico?

Exemplo:

Sintetico:
Grupo: Grupo de produto
Produto------------------Saldo Inicial--------------------Entrada--------------------Saída----------------Saldo
Filtro XPTO-------------10,000---------------------------5,000-----------------------7,000----------------8,000

No caso do Analítico como ficaria?

**Comment by renatogolden** [comment]
Filtros: Grupo de produtos[ produto[ data inicio[ data final[ tipo de movimentação[  departamento[ estoque.
Exemplo: Analitico
""Se marcar grupo""": Lubrificantes (separar apenas por grupo)
""Se marcar departamento" separar os departamentos...
20/09/2018 08:00  Entrada Estoque Lubrax 15w50------50 und-----1,00------50,00 --  NomeDepart
20/09/2018 09:00  Saída                   Lubrax 15w50------1 und-- ---1,00------1,00 --    NomeDepart
20/09/2018 10:00  Saída                   Lubrax 15w50------1 und--- --1,00------1,00 --    NomeDepart
20/09/2018 10:00  Saída                   Lubrax 15w50------3 und--- --3,00------3,00 --    NomeDepart
21/09/2018 11:00  Saída Ajuste        Lubrax 15w50------2 und--- --2,00------2,00 --    NomeDepart
22/09/2018 08:00  Entrada Ajuste    Lubrax 15w50------1 und--- --1,00------1,00 --    NomeDepart

sintético: (resumir todas as saídas em um mesmo item por movimentação)
20/09/2018 08:00  Entrada Estoque Lubrax 15w50------50 und-----1,00------50,00 --    NomeDepart
20/09/2018 09:00  Saída                   Lubrax 15w50---- -29 und-----29,00-----29,00 --   NomeDepart
21/09/2018 11:00  Saída Ajuste        Lubrax 15w50------2 und--- --2,00------2,00 --      NomeDepart
22/09/2018 08:00  Entrada Ajuste    Lubrax 15w50------1 und--- --1,00------50,00 -  -  NomeDepart

**Comment by marcioelias** [comment]
Poderiam analisar a saída desse relatório analítico de movimentação de produtos para me dizerem se está de acordo?

![image](https://user-images.githubusercontent.com/2084051/46258896-c21c0980-c4a7-11e8-80e3-3c38f6e0f3a1.png)

**Comment by marcioelias** [comment]
Criado relatório de movimentações de produtos, com filtros por:
 - Data a partir de
 - Data até
 - Data de até
 - Tipo de movimentação
    - Entrada 
    - Saída
    - Todos
 - Estoque
    - Grupo de Produtos
         - Produtos

Com 2 modalidades:
 - Sintético: 
    - Agrupado por Estoque
    - Apresenta um produto por linha
    - Total de Entrada segundo os critérios
    - Total de Saída segundo os critérios

 - Analítico
    - Agrupado por Estoque / Produto
    - Uma linha para cada movimentação 
    - Total de Entrada/Saída das movimentações por produto, conforme os critérios informados para gerar o relatório
