### ISSUE TITLE
Entrada de estoque

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#5]
Não aparece o grid da data quando clicamos no botao. e ao salvar da erro., mesmo digitando manualmente

 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function format() on boolean

                'fornecedor_id' => 'required',
                'items' => 'required|array|min:1'
            ]);
            try {
                DB::beginTransaction();
                $entradaEstoque = new EntradaEstoque($request->all());
                
                $dataDoc = \DateTime::createFromFormat('d/m/Y H:i', $request->data_doc);
                $dataEntrada = \DateTime::createFromFormat('d/m/Y H:i', $request->data_entrada);
                
                $entradaEstoque->data_doc = $dataDoc->format('Y-m-d H:i:s');
                $entradaEstoque->data_entrada = $dataEntrada->format('Y-m-d H:i:s');
 
                $entradaEstoque->valor_total = 10; //arrumar depois
 
                if ($entradaEstoque->save()) {
                    $entradaEstoque->entrada_estoque_items()->createMany($request->items);
 
                    MovimentacaoProdutoController::entradaEstoque($entradaEstoque);
 
                    DB::commit();
                    Session::flash('success', __('messages.create_success', [
                        'model' => 'entrada_estoque', 
                        'name' => $entradaEstoque->nr_docto
                    ]));
 
                    return redirect()->action('EntradaEstoqueController@index');
                } else {

**Comment by renatoxokleng** [comment]
NO cadastro de abastecimento tbm nao aparece a data ao clicar. acredito que deva ser geral.

**Comment by marcioelias** [comment]
Já foi resolvido tmb
