### ISSUE TITLE
cadastro de configuracao ftp

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#50]
criar tela para cadastro de configutacoes do ftp. endeço. usuario e senha

**Comment by marcioelias** [comment]
No menu Configurações > Configurações

Acesso somente para usuários com o perfil **Super**.

Configurações da conta de FTP, porém foi criado uma classe para possibilitar alterção de outras configurações do sistema no futuro.

Alterado todas as ações que importam/exportam arquivos do FTP para carregar os parâmetros configurados nesta tela antes de efetuar qualquer ação.
