### ISSUE TITLE
Relatorio de abastecimento  - Bicos

### ISSUE THREAD

**Issue by renatogolden** [marcioelias/goldenfrota#53]
Relatorio de abastecimento  - Bicos
O relatório ja existe, mas coloca uma opção para mostrar a média (sim ou nao)

**Comment by marcioelias** [comment]
Implementado um campo nos parâmetros do formulário, para informar se vai mostrar a média no relatório ou não. O padrão é não mostrar. 

Se selecionado para mostrar a média, a mesma irá aparecer em uma coluna ao lado da placa do veículo.
