### ISSUE TITLE
Inventário

### ISSUE THREAD

**Issue by renatogolden** [marcioelias/goldenfrota#54]
Colocar opção de criar inventário:
Estoque
ou
Grupo de produto
ou
Produto

**Comment by marcioelias** [comment]
Se eu selecionar por:
 - Estoque: Todos os produtos relacionados aquele estoque
 - Grupo de Produtos: Todos os produtos daquele Grupo de Produto selecionado
 - Produto: Somente o produto selecionado.

Porém precisamos prever o multi-estoque, então o Estoque tem que ser obrigatório, deve ser sempre selecionado, o que pode ser feito é além do estoque, selecionar algum Grupo de Produtos ou Produto em específico para aquele estoque.

**Comment by marcioelias** [comment]
Desenvolvimento realizado no caso de uso de inventário, melhorando vários aspectos de todo o processo.

- Adicionado relação de Grupo de Produto a tela de Cadastro de Inventário (os grupos estão condicionados a terem produtos relacionados com o estoque selecionado).
- Adicionado relação de Produtos a tela de Cadastro de Inventários (os produtos estão relacionados ao Estoque, e ao Grupo de Produtos previamente selecionados)

> Colocar opção de criar inventário:
Estoque
ou
Grupo de produto
ou
Produto

Na verdade ficou:
- Estoque ou
- Estoque - Grupo Produtos ou
- Estoque - Grupo Produtos - Produto

- Alterado o componente para informar se o inventário está ou não fechado na tela de Alteração de Inventário, de um dropdown para um checkbox (toggle).
- Ajustado os campos data de abertura e data de fechamento na tela de Alteração de Inventário
  - Data de abertura não era mostrado
  - Data de fechamento é automaticamente preenchido ao setar o inventário como fechado.
- Removido coluna "Ajustado" da tela de visualização/relatório de conferência de inventário. A finalidade desse campo inicialmente era indicar se um produto já teve sua contagem ajustada ou não, mais em função dos últimos desenvolvimentos não teve mais utilidade e não estava sendo utilizado, servindo apenas para gerar dúvidas na utilização da ferramenta.
