### ISSUE TITLE
Problema ao editar um usuario

### ISSUE THREAD

**Issue by renatogolden** [marcioelias/goldenfrota#55]
Fui alterar o nome e percebi que ele ta fazendo isto:

array:7 [▼
  "_token" => "DaiPJ8bomQmfmFdMG2ScQ4FwAKM08GUHcQEcltnf"
  "_method" => "PUT"
  "name" => "Golden Service"
  "ativo" => "1"
  "email" => "goldenservicenet@gmail.com"
  "password" => "72d836"
  "password_confirmation" => "72d836"
]

**Comment by marcioelias** [comment]
Resolvido.
