### ISSUE TITLE
Problema fechamento inventario

### ISSUE THREAD

**Issue by renatogolden** [marcioelias/goldenfrota#56]
Produto nao movimentado, está ficando com -1 no campo 'quantidade ajustada'.

**Comment by renatogolden** [comment]
Colocar campo observação/motivo no cadastro do inventário

**Comment by marcioelias** [comment]
> Colocar campo observação/motivo no cadastro do inventário

Movido para um novo issue #58

**Comment by marcioelias** [comment]
Esse valor negativo em produtos que não foi informada a contagem para ajuste, se deve ao fato que, não seria possível a contagem de um produto negativo no estoque físico, mais a quantidade zero é possível. Sendo assim, sempre que não for informado a quantidade contada, o sistema atribui o valor -1, para identificar que aquele produto não teve a contagem informada.

A quantidade ajustada por sua vez, se da pela quantidade contada menos o saldo em estoque, pelo fato da quantidade contada estar negativa. 

Alterado a impressão do inventário para quando a quantidade contada for negativa, não mostrar valor no campo de ajuste, e também foi alterado o campo de ajuste para mostrar o sinal (-) quando o ajuste foi a diminuição do estoque, e (+) quando foi a soma ao saldo em estoque.
