### ISSUE TITLE
Campo de pesquisa nos cadastros

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#62]
Adicionar a todas telas de cadastroa opcao de informar o campo para a pesquisa.

**Comment by marcioelias** [comment]
Incluído campo que possibilita ao usuário especificar por qual campo da tabela gostaria de efetuar uma consulta.

Em caso de campos do tipo inteiro/numérico a consulta procura por um match (igualdade completa de valor com o valor informado) em caso de campo do tipo text/string é feita uma pesquisa onde o dado informado faça parte do valor dos campos.
