### ISSUE TITLE
melhoria na saida do estoque/cliente/departamento

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#7]
Ao lancar uma saida é nescessário informar um cliente e um departamento associado a ele. da maneira que esta teria que cadastrar um departamento para cada cliente...
Estou avaliando se ao inves do campo cliente, colocar o campo 'funcionário`

**Comment by marcioelias** [comment]
Departamento não é obrigatório

**Comment by marcioelias** [comment]
Na verdade, o departamento não é obrigatório desde que o cliente selecionado não tenha nenhum departamento relacionado cadastrado.

Se o cliente tiver algum departamento cadastrado para ele, obrigatoriamente o sistema está selecionando um.

Se quiserem podemos modificar isso.

**Comment by renatoxokleng** [comment]
Mudar a ordem do filtro padrão, mostrar os últimos lançados primeiro.

**Comment by renatoxokleng** [comment]
Aél deste filtro do filtro de movimentacao de combustivel tamém mostra sempre como primeiro abastecimento um fora da sequencia (olha a hora).

**Comment by marcioelias** [comment]
Como pode ver na imagem, a ordem é pela data/hora do abastecimento.

![image](https://user-images.githubusercontent.com/2084051/46188854-eae2aa00-c2c1-11e8-8639-046ad7648955.png)

Caso não seja nesta tela a que se refere, abrir um novo issue detalhando o caminho para verificar.
