### ISSUE TITLE
Criar relatório de movimentacao de produtos

### ISSUE THREAD

**Issue by renatoxokleng** [marcioelias/goldenfrota#8]

**Comment by marcioelias** [comment]
Feito.

Falta testar e avaliar os dados e a forma de apresentação.

Se tiver que alterar ou adicionar algo, informar por aqui, se estiver tudo Ok, confirmar para poder fechar essa implementação.

**Comment by renatoxokleng** [comment]
Relatorio esta ok. se nao for dificil, colocar tipo de agrupamento . data ou tipo de mocimentçao e totalizar.

**Comment by marcioelias** [comment]
A totalização seria por produto?

**Comment by renatoxokleng** [comment]
Isso, totalizar quantidade.
Importante ter o Filtro: Tipo de movimentação (entrada, saída, todos)

**Comment by marcioelias** [comment]
Migrado para o Issue #49
